#!/bin/bash

CC="cc -std=c99 -O -Wall"
AR="ar -rs"

export LIBRARY_PATH="/opt/local/lib:$LIBRARY_PATH"
export C_INCLUDE_PATH="/opt/local/include:$C_INCLUDE_PATH"

[[ -d obj/ ]] || mkdir obj/
[[ -d lib/ ]] || mkdir lib/

$CC -o obj/flags.o -c src/flags.c
$CC -o obj/fmemopen.o -c src/fmemopen.c
$CC -o obj/open_memstream.o -c src/open_memstream.c
$CC -o obj/open_wmemstream.o -c src/open_wmemstream.c
$AR -c lib/libmemstream.a obj/*.o
