#!/usr/bin/env bash

source ./common

if [[ -z "$INSTALL_PREFIX" ]] ; then INSTALL_PREFIX="/usr/local" ; fi
INSTALL_LIB_PREFIX="$INSTALL_PREFIX/lib"
INSTALL_INCLUDE_PREFIX="$INSTALL_PREFIX/include"
INSTALL_MAN_PREFIX="$INSTALL_PREFIX/share/man"

$INSTALL -m 644 "$BUILD_LIB_DIR/$LIBRARY_NAME.a" "$INSTALL_LIB_PREFIX" &&
$INSTALL -m 644 "src/"memstream.h "$INSTALL_INCLUDE_PREFIX" &&
$INSTALL -m 644 "man/"memstream.3 "$INSTALL_MAN_PREFIX/man3" &&
for man_page in fmemopen open_memstream open_wmemstream ; do
    $LN "$INSTALL_MAN_PREFIX/man3/memstream.3" "$INSTALL_MAN_PREFIX/man3/$man_page.3"
done &&

exit 0 # EX_OK
